### PR TITLE
Docker compose implementation

### PR DESCRIPTION
**Pull request by SarunasAzna**
Docker-compose implementation.
These changes allows developer to run the project with one command - `docker-compose up`.

### CODE REVIEW

**Comment by joel-simon** [comment]
Awesome, thanks!

**Comment by SarunasAzna** [comment]
;) question is, is it possible to cache tensorflow module? Those few
minutes each time is a bit annoying :(

**Comment by joel-simon** [comment]
For downloading or loading into ram? Probably don't want to stick the whole file in the docker, it will get saved locally so as long as you reuse the docker image it should be ok?

**Comment by SarunasAzna** [comment]
As per docker image reuse - if the file is in shared dir - all fine, if not
- docker will be pretty much in the same state as it is defined on
Dockerfile even if you reuse it :( As per first part of the question - I
guess downloading, though i am not sure since all of my tensorflow exp is
that those few hours with your repo.. But what would be good - cache some
of the things done from here
https://github.com/joel-simon/ganbreeder/blob/master/gan_server/server.py#L20
to
https://github.com/joel-simon/ganbreeder/blob/master/gan_server/server.py#L36
.

**Comment by SarunasAzna** [comment]
awesome website btw :)

**Pull request merged**
